# Generated by Django 6.0.1 on 2026-01-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='metodo_pago_preferido',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_MOVIL', 'Pago Móvil / Zelle'), ('TARJETA', 'Tarjeta')], default='EFECTIVO', max_length=20, null=True),
        ),
    ]
